### ISSUE TITLE
identify if a given tracker is on my phone 

### ISSUE THREAD

**Issue by l1git** [Exodus-Privacy/exodus-android-app#1]
On alpha android app it would be great to be able to select a tracker from a list (alternatively from the report of a specfic app) and then be able to see all apps on my phone that contains the culprit.

This would allow to remove all occurrences of a given tracker.

**Comment by tdelmas** [comment]
A list of all the trackers present on the phone could be nice too

**Comment by borsini** [comment]
@Schoumi I can work on that if you're interested.

It requires some UI/UX design though. I think that [bottom navigation](https://material.io/design/components/bottom-navigation.html) would be a great option to switch from the application list to a potential tracker list. A click on a tracker cell could then open the application list filtered to only display apps having this tracker. 

What do you think ?

**Comment by Schoumi** [comment]
@borsini 
Bottom navigation with 2 choice (Application List/Tracker List)
For the Tracker List. What you propose seems good to me.
A search bar for tracker and on tracker cell a number of app containing this tracker will be cool

it was my plan for this part but feel free to do it if you want to :)

**Comment by simpnu** [comment]
@borsini @Schoumi Do we want to display the trackers which are not present on the phone then? (maybe only greyed out?)

**Comment by Schoumi** [comment]
Maybe with an option show/hide but not always and yes should be visible that there not on the phone

**Comment by Jean-BaptisteC** [comment]
In 2.2.1, we show trackers presents on app phone.
Idem for rewrite in Kotlin
