### ISSUE TITLE
Filters doesn't work after consult trackers

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#101]
Issue:
- Device: Pixel 6
- OS: Android 12
- EP Version: Preview

How reproduce:
- Go to trackers tab
- Consult a tracker
- Go back to my apps tab
- Use filters
- Filter doesn't work

**Comment by Jean-BaptisteC** [comment]
| Version | Detected |
| --- | --- |
| Android 5 | Yes |
| Android 7 | Yes |
| Android 8 | Yes |
| Android 12 | Yes |

**Comment by Jean-BaptisteC** [comment]
Other scenario:
- Consult report
- Go to trackers tab
- Go back to my apps tab
- Filter doesn't work

The issue appears when you consult reports or trackers and switch tab.

**Comment by ItsIgnacioPortal** [comment]
Verified on v2.2.1, Android 9.
