### ISSUE TITLE
Add support for landscape mode

### ISSUE THREAD

**Issue by Rudloff** [Exodus-Privacy/exodus-android-app#11]
Hello,

I tried the app (1.0.4) on an Android 4.2 tablet and it forces the display in portrait mode (which can be annoying when the tablet is attached to a keyboard).

**Comment by simpnu** [comment]
Hi @Rudloff!
Could you please confirm that the problem has been fixed by https://github.com/Exodus-Privacy/exodus-android-app/pull/12? Thanks! :)

**Comment by Rudloff** [comment]
I confirm this is fixed in 1.1.1.
