### ISSUE TITLE
Migrate from Travis CI to GitHub Actions

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/exodus-android-app#113]
Following discussions in #112: https://github.com/Exodus-Privacy/exodus-android-app/pull/112#issuecomment-1003398605

> AFAIK there were some changes in Travis indeed and we tried to move to GitHub Actions for all our repositories. Should probably do the same change here.

**Comment by theimpulson** [comment]
@pnu-s can this issue be assigned to me?

I tried doing it and it seems to be working fine for me in https://github.com/theimpulson/exodus-android-app/commit/6d10b4c3f3dcf69f2e639af74b6b6cfe3292744e. Would you like me to push it with #112?

**Comment by pnu-s** [comment]
Sure, thanks again @theimpulson :tada: 

If that's possible, I would advise to do it separately (in 2 different PR), so that it is easier to review and approve.
