### ISSUE TITLE
Document various productFlavors and their differences

### ISSUE THREAD

**Issue by theimpulson** [Exodus-Privacy/exodus-android-app#118]
Currently, there seems to be no documentation or README explanation for the various flavors which makes it hard to understand why they exist. Create a wiki page or section in README that documents:

- The different available flavors,
- Their key differences from one another (possibly in a chart/table for ease of comparison),
- Goal as to why these flavors were created.

Having documentation available for different flavors will allow contributors to gain more insight on how this application work and what are the requirements for certain flavors to keep them passing with future changes.

Currently, available flavors are:

- exodus_google,
- amal_google,
- fedilab_google,
- exodus_fdroid,
- amal_fdroid, and
- fedilab_fdroid

Source: https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/build.gradle#L32

**Comment by jfoucry** [comment]
Hello,

We don't have documentation of those flavors (for now), but after some check I can explain thems.

exodus_google → the build for Exodus Google Play
amal_google → a specific build for the French Education Mnisitry for Google Play
fedilab_google → a specific build made by the developer of fedilab (who help us some time) for Google Play
And the same organization for fdroid 

Hop this help your interstanding

**Comment by Jean-BaptisteC** [comment]
With latest version, i have reduce numbers of flavors
Now we have only same version for Google Play and Fdroid
