### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by jfoucry** [Exodus-Privacy/exodus-android-app#121]
Hello folks,

I just checkout the project in AndroidStudio and many files are in error because of missing a package:

`import org.eu.exodus_privacy.exodusprivacy.databinding.AppItemBinding;`

Can't find it in the source file list. Did I miss something?

**Comment by jfoucry** [comment]
Hum…

I just build the project without any error. It seems the "missing file" is generated at compile time. I can't understand how. If some one could explain I will appreciate.

**Comment by theimpulson** [comment]
@jfoucry the project uses a build feature called `data binding`. It is quite similar to [view binding](https://developer.android.com/topic/libraries/view-binding) described here which explains how it works. In brief, to interact with the XML UI components, Android Studio generates various binding classes at runtime if the feature has been enabled. This allows an easy way to work with them ensuring that views are not null and have type safety.

**Comment by jfoucry** [comment]
Thanks @theimpulson. I understood that it was not missing when I recompile the project and all works fine
Thanks for the link,.

I close the false issue.
