### ISSUE TITLE
Add exodus-standalone to Github Actions

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/exodus-android-app#134]
I think we could scan the built application with GitHub Actions with https://github.com/Exodus-Privacy/exodus-standalone for each merge request.

This would:
* make sure that we do not add any tracker
* do what we recommend to others :)
* probably add a new example into exodus-standalone documentation

**Comment by Jean-BaptisteC** [comment]
Example to execute exodus-standalone in workflow
I don't have find how doing uses and run in the same action
```
 - name: Install Docker 
      uses: docker-practice/actions-setup-docker@master
 - name: Execute exodus-standalone
      run: |
              docker run -v $(pwd)/app/build/outputs/apk/exodus/release/app-exodus-release-unsigned.apk:/app.apk --rm -i exodusprivacy/exodus-standalone
```

**Comment by pnu-s** [comment]
There is a way to use Docker images directly in GitHub Actions, see https://www.petefreitag.com/item/903.cfm

That would be something along the lines of:

```
- name: Execute exodus-standalone
  uses: docker://exodusprivacy/exodus-standalone:v1.3.0
  with:
    args: ...
```

Just need to provide args and it should do the trick!
No need to install Docker in this case

**Comment by Jean-BaptisteC** [comment]
Just execute step "Execute exodus standalone" works!
