### ISSUE TITLE
Drop following manifests

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/exodus-android-app#140]
@jfoucry the following manifests should also be dropped, now that we have the permission in the main manifest:

- https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/src/fdroid/AndroidManifest.xml
- https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/src/google/AndroidManifest.xml

Might need to add the `tools:ignore` tag as well.

_Originally posted by @theimpulson in https://github.com/Exodus-Privacy/exodus-android-app/issues/136#issuecomment-1047390842_

**Comment by Jean-BaptisteC** [comment]
Tested today, it's works i push commits in release-v2.2.1
