### ISSUE TITLE
Apk requires prominent disclosure

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/exodus-android-app#143]
Seems like Google wants to be more cautious with a privacy-focus app like ours than with other apps, but here we go.

> Your app is uploading users' Installed Application information to https://reports.exodus-privacy.eu.org without a prominent disclosure. Prior to the collection and transmission, it must prominently highlight how the user data will be used, describe the type of data being collected and have the user provide affirmative consent for such use.
> 
> For further details on the valid prominent disclosure requirement, please review the “[Prominent Disclosure & Consent Requirement](https://notifications.google.com/g/p/AD-FnEwM9LluzpzXyS-c3NCSVfKjzcRm9OunQswPTZr5mqP8wu-0dYL2FJuQc6ZvAVYM2XBxk74SNy1jHXmAnoMOk34F4WDzWyzuimA6PHEyMUhUfk8thwdZIGZ6PXMjCZ94KDNR7blnET0)” section under the User Data policy.

To be honest, I'm a bit surprised by the following:

> In cases where users may not reasonably expect that their personal and sensitive user data will be required to provide or improve the policy compliant features or functionality within your app

What we need to do:
* Add a pop-up when a user first start the application, with a content such as: `'[This app] collects/transmits/syncs/stores [type of data] to enable  ["feature"], [in what scenario].`
* If the user consents, go on with the normal behavior of the app
* If they don't, quit the application

Extract from [Google's documentation](https://support.google.com/googleplay/android-developer/answer/10144311?visit_id=637814938568922523-1945087246&rd=1&hl=en-GB):
![image](https://user-images.githubusercontent.com/6069449/155853358-c30bb7b7-8193-43c4-8f98-bd882b322aaa.png)

**Comment by Jean-BaptisteC** [comment]
App is available on Google Play, i close this issue
