### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [Exodus-Privacy/exodus-android-app#153]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found one warning (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on exodus-android-app (or its library dependencies). We documented this issue in a private gist for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share this gist with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve exodus-android-app's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by theimpulson** [comment]
Please share here on the issue. Also please keep in mind that we are currently in the process of rewriting the application with new libraries and language, thus it will be better to also have this report on the [rewrite ](https://github.com/Exodus-Privacy/exodus-android-app/tree/kotlinRewrite) branch if possible.

**Comment by Jean-BaptisteC** [comment]
Problems of cryptography is referenced [here](https://lgtm.com/projects/g/Exodus-Privacy/exodus-android-app/alerts/?mode=list) ?
If you want you can contacted association on [IRC](https://matrix.to/#/#exodus-android-app:matrix.org).
