### ISSUE TITLE
Improve bottom navbar

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#159]
![Screenshot 2022-04-23 at 11-11-11 Figma](https://user-images.githubusercontent.com/87148630/164888244-d82acdf5-940a-443c-a8ca-3783ffb92462.png)

* Replace this [icon](https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/src/main/res/drawable/ic_baseline_analytics_24.xml) by [tracker icon](https://github.com/Exodus-Privacy/exodus-android-app/blob/44ec39c5be0935cff1a1b0948c4b7d392463e550/app/src/main/res/drawable/ic_tracker.xml)

List of assets (filled/unfilled) used:
* [Grid On](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Agrid_on%3A)
* [Visibility](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Avisibility%3A)
* [Info](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Ainfo%3A)
*  And if it's no too complicated maybe animate icons

**Comment by theimpulson** [comment]
Done in https://github.com/Exodus-Privacy/exodus-android-app/commit/2924d42bb864068010fab046b0164c33e95a9c48
