### ISSUE TITLE
Is the "coelib.c.coulus" library detected by this app?

### ISSUE THREAD

**Issue by freecycler** [Exodus-Privacy/exodus-android-app#161]
It seems like the kind of thing users might want to know about, given what it has been seen to phone home with. But I'm not clear how to know what items are in the database to be checked for.

more details:
https://blog.appcensus.io/2022/04/06/the-curious-case-of-coulus-coelib/

**Comment by pnu-s** [comment]
Hi,
Thanks for reporting this!

You can see all trackers detected here: https://reports.exodus-privacy.eu.org/en/trackers
(I'm pretty sure the list should be available from the app as well)

I have just added Coulus Coelib to our database, it should show whether it is detected in the next hours/days.
