### ISSUE TITLE
[FEATURE] Filter apps based on X

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Exodus-Privacy/exodus-android-app#165]
Emphasis on **filter**. Filtering is not the same as sorting. I propose the following filters:

- Has Internet permissions
- Has trackers
- Has unblockable trackers\*

\* Unblockable trackers are those trackers that have a _code detection rule_ but no _network detection rule_, for example [Microsoft Visual Studio App Center Analytics ](https://reports.exodus-privacy.eu.org/en/trackers/243/). Because these trackers don't have a network dectection rule, they can't be blocked by generic pre-made DNS filters.

**Comment by ItsIgnacioPortal** [comment]
I disagree:
- _Has internet permission_ would help users to notice if an app is collecting analytics, but is not uploading it directly, and is instead using another app from the same developer as a proxy.

- _Has trackers_ could be renamed to _Has no known trackers_. Displaying FOSS apps that the user already knows have 0 trackers is pointless.

- _Has unblockable trackers_: Yeah, that's the point. That we can help the user detect if an app has a tracker with no known network detection rule

**Comment by yoshimo** [comment]
By source, paid or not, whether the version installed has been scanned already

**Comment by ItsIgnacioPortal** [comment]
@Jean-BaptisteC this feature seems pretty basic (important) on an app like this. I ask you to please reconsider adding it to future plans
