### ISSUE TITLE
[FEATURE] Share playstore link to app to see trackers

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Exodus-Privacy/exodus-android-app#166]
This feature would make it even faster to see how many trackers an app has before installing it. Without this feature, the only options are already having the browser open with the exodus privacy site, or using Aurora Store.

- The first option is clumsy, as you have to constantly go back and forth between apps and browser tabs.
- The second option is annoying for discovering apps, because it lacks the recommendations algorithm that the Google Playstore has.

**Comment by ItsIgnacioPortal** [comment]
nvm, I didn't notice this was already a feature

**Comment by Nive9** [comment]
It would be nice if this could be reopened since that functionality seems to have been removed in v3. 

Was really useful and would be great if it could be re-implemented again.

**Comment by Jean-BaptisteC** [comment]
Yes, it's planned, but we have not enough time to re-add this feature for now.
We want improve this feature with new IHM to show reports (replace pop-up by fragment full page).
