### ISSUE TITLE
[FEATURE] Sort apps based on modified date

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Exodus-Privacy/exodus-android-app#167]
This would make it easier to check the trackers of recently installed apps, or apps that have been updated recently

**Comment by Jean-BaptisteC** [comment]
That's a good idea.
But we don't analysed apps after each new version.
From Play Store or Fdroid, you can check reports

- On store, select anyone app in list
- use share button
- On list, select Exodus
- We show trackers about app
- Or submit app, if we have no reports on app

**Comment by ItsIgnacioPortal** [comment]
> But we don't analysed apps after each new version.

[Perfect365](https://reports.exodus-privacy.eu.org/en/reports/list/?filter=most_trackers) has several versions of scans listed. Exodus clearly _does_ scan new app versions.

**Comment by Jean-BaptisteC** [comment]
You take in example the worst app in our database. 😂
Ok, we can add on 3.0 version this sort element
Sort is based on reports date creation (the first element in list is the latest report)
Is it ok for you, if i close this issue and add information on #163 to centralize informations ?
