### ISSUE TITLE
[FEATURE] Notify the user if a previously installed app has a new tracker

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Exodus-Privacy/exodus-android-app#168]
This feature would compare a previous scan to a new scan, and if an app that was already scanned has had a new tracker added, notify the user. This would probably be best implemented by also implementing #94

**Comment by Jean-BaptisteC** [comment]
Duplicate of [exodus#427](https://github.com/Exodus-Privacy/exodus/issues/427)
If we add this feature on website, we add this feature on android app.

**Comment by ItsIgnacioPortal** [comment]
This issue is not a duplicate, as implementing this in the app does not necesarily need any server side modifications.
