### ISSUE TITLE
Percentage bar is wrong

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#174]
<img src="https://user-images.githubusercontent.com/87148630/170000312-4c1726cd-b14d-4602-8af0-9802582013b8.png" width="300">

Percentage bar doesn't follow percentage and sometimes percentage bar dissapear after consult any tracker.

**Comment by theimpulson** [comment]
This should be fixed with https://github.com/Exodus-Privacy/exodus-android-app/commit/dd4b1adbf8e5c42d1ee846530ec28f4c90e6bc45
