### ISSUE TITLE
Percentage of trackers is incorrect

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#176]
Android 12 - Pixel 6

How reproduce:

- Consult reports with trackers
- Consult trackers from reports
- Percentage of trackers is wrong

Example:

- Google Firebase Analytics Present in 100% (21 apps) on trackers from reports
- Google Firebase Analytics Present in 80% (21 apps) on trackers from trackers fragment

**Comment by Altonss** [comment]
The way the percentage is calculated seems weird to me. I get that one tracker has the percentage of `50% (2 apps) of your applications` despite having a lot of apps (more then 20) containing no trackers. So this 50% percentage seems wrong, or is it calculated based on the total amount of apps containing trackers? If this is the case, maybe the string should be updated to contain this info...

**Comment by Jean-BaptisteC** [comment]
I'm remember percentage exclude apps without reports and apps without trackers.
You can update if you want to take all installed apps with or without reports in percentage :)

**Comment by Altonss** [comment]
> I'm remember percentage exclude apps without reports and apps without trackers. You can update if you want to take all installed apps with or without reports in percentage :)

Thanks for the info. What would make more sense do you think, use the total of all installed apps? I think this would make more sense, but maybe this should be discussed :)

**Comment by Jean-BaptisteC** [comment]
I think to show the right percentage, the best way is take all apps with reports
Because take apps without reports is not right because, if we take this -> we tell apps without reports have not trackers and it's not the truth.

**Comment by Altonss** [comment]
> I think to show the right percentage, the best way is take all apps with reports Because take apps without reports is not right because, if we take this -> we tell apps without reports have not trackers and it's not the truth.

Yes the right percentage of a certain tracker should be number of apps having this tracker/number of analysed apps by exodus

**Comment by Altonss** [comment]
I tried to fix the issue, but I don't know how to retrieve the total amount of analysed apps by exodus from inside this file https://github.com/Exodus-Privacy/exodus-android-app/blob/fc156374df41a9794eaa4e22fb27e0a16afdf03b/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/model/TrackersRVAdapter.kt#L48
Has anyone an idea?

**Comment by Jean-BaptisteC** [comment]
Maybe we can used SQL request ?
https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/app/ExodusApplicationDao.kt

**Comment by Altonss** [comment]
> Maybe we can used SQL request ? https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/manager/database/app/ExodusApplicationDao.kt

Yes but then I don't know how to call it from inside TrackersRVAdapter.kt ...

**Comment by Jean-BaptisteC** [comment]
Like this
https://github.com/Exodus-Privacy/exodus-android-app/blob/5b145fc03178f8aff909b6cb12dd0dd9fad18771/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailViewModel.kt#L27

or this

https://github.com/Exodus-Privacy/exodus-android-app/blob/5b145fc03178f8aff909b6cb12dd0dd9fad18771/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/TrackersViewModel.kt#L15

Maybe create new SQL request
`SELECT COUNT(*) FROM exodusapplication`

**Comment by Altonss** [comment]
> Like this
> 
> https://github.com/Exodus-Privacy/exodus-android-app/blob/5b145fc03178f8aff909b6cb12dd0dd9fad18771/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailViewModel.kt#L27
> 
> or this
> 
> https://github.com/Exodus-Privacy/exodus-android-app/blob/5b145fc03178f8aff909b6cb12dd0dd9fad18771/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/trackers/TrackersViewModel.kt#L15
> 
> Maybe create new SQL request `SELECT COUNT(*) FROM exodusapplication`

Thanks, I will look at this :)

**Comment by Jean-BaptisteC** [comment]
We have discussed, we don't want update calcul about percentage, this issue is only use to fix incorrect percentage.
