### ISSUE TITLE
Add controls about Internet with snackbar

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#178]
Add controls about Internet with snackbar (like 2.0 version) to use app without Internet

**Comment by Jean-BaptisteC** [comment]
Add [snackbar](https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#Snackbar(androidx.compose.ui.Modifier,kotlin.Function0,kotlin.Function0,kotlin.Boolean,androidx.compose.ui.graphics.Shape,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,kotlin.Function0)) with string `No Internet connection` and link to settings (Wifi or mobile data)
Remove `X` on snackbar
Snackbar be show above bottom bar
Find a solution for ExodusUpdateService.kt
Example: If user disable Internet during refresh, stop actualization without crash

**Comment by J-Jamet** [comment]
I'm not familiar with compose and Material3, as the current code is in XML, I'm using a coordinatorLayout in an XML first.
