### ISSUE TITLE
Expand detection methods

### ISSUE THREAD

**Issue by licaon-kter** [Exodus-Privacy/exodus-android-app#18]
How does the app detect them?

Eg. I have [ACR](https://reports.exodus-privacy.eu.org/reports/search/com.nll.acr) installed from [APK](https://www.apkmirror.com/apk/nll/call-recorder-acr/) yet I get a screen with _no apps from source_.

What are the conditions? Google Play store enabled/installed? Can't you track by hash? Signature?

/LE: Ok, so you check [what app installed the package](https://github.com/Exodus-Privacy/exodus-android-app/blob/13289fcfafcbd557b1b5d6062368b62ce7c905d9/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/adapters/ApplicationListAdapter.java#L76) and if it's `com.android.vending` then you consider them for testing.

**Comment by Schoumi** [comment]
App are not test by android app, only filtered. Yes if you install from apk, we can't know from where you have it and if the report is still valid. Trackers may not be exist in your version.
We try to add more method to identify a source but for now this is the only one.

**Comment by Tonat** [comment]
[AdAway](https://f-droid.org/en/packages/org.adaway/) has a feature called "Scan for adware" which -- as far as I can see from their [source code](https://github.com/AdAway/AdAway/blob/master/AdAway/src/main/java/org/adaway/util/ScanAdwareLoader.java) does the following:
It inspects all the activities, receivers and services of all installed packages and compares them to a  list of sdk names of known advertising companies. They hardcode a list `AD_PACKAGE_PREFIXES`, but maybe Exodus could to the same thing with a dynamic, downloaded list containing known prefixes of ad **and** tracking sdks?
It's not bulletproof of course, but it's a start :)

**Comment by killoid** [comment]
i download all my apps from yalpstore. & AFAIK the apps are straight downloaded from google play. so, it would be really helpful to add yalpstore for checking besides google play.

**Comment by Schoumi** [comment]
@Tonat this is not the goal of this app. This app will not analyse anything. Maybe we make another to make some analysis but not this one.

**Comment by lionirdeadman** [comment]
I think you should use the hash + package name to tell the server if it scanned it or not instead of what app it got installed from. This would make it much less reliant on it being installed by the Gplay application and still verify that the trackers are really there. 

(The exception to the rule would be beta updates but then the scan would not be reflecting reality anyways so it doesn't matter)

**Comment by counter-reverse** [comment]
> How does the app detect them?

Interesting question. You can get all the answers you want by reading the source code of the core of the application at the adress: https://github.com/Exodus-Privacy/exodus-core.

The executable binary code is read statically (with not any execution). You can learn that the full command is 'dexdump <extracted apk file>/classes*.dex | perl -n -e\'/[A-Z]+((?:\w+\/)+\w+)/ && print "$1\n"\'|sort|uniq' % from the source code at https://github.com/Exodus-Privacy/exodus-core/blob/v1/exodus_core/analysis/static_analysis.py#L188. you can know more by downloading dexdump on linux and then run man dexdump. 

I have to understand the command too. I will make you stay tuned on this issue.

> Eg. I have [ACR](https://reports.exodus-privacy.eu.org/reports/search/com.nll.acr) installed from [APK](https://www.apkmirror.com/apk/nll/call-recorder-acr/) yet I get a screen with _no apps from source_.

No idea.

> What are the conditions? Google Play store enabled/installed? Can't you track by hash? Signature?

I worked on the icon.  APK icon comes from the folder where exodus-core is installed.  if the APK icon does not exist yet, then the application icon is installed by gplaycli, the command line interface of google play. if it does not exists, it is downloaded from internet. I imagine it is similar with the apk file. 

If you are interested in download an apk file manually to check it from your computer, fell free to go to https://apkpure.com/.

**Comment by Jean-BaptisteC** [comment]
#156
