### ISSUE TITLE
Bug in display of trackers!

### ISSUE THREAD

**Issue by Altonss** [Exodus-Privacy/exodus-android-app#194]
The tracker "Google Analytics" is present in the trackers list despite being in no app. This is maybe due to the presence of the "Google Firebase Analytics" tracker. It says Google analytics is present in 1 app on the list, but after clicking on it, it says it is present in 0 apps.
![_20220807_123737](https://user-images.githubusercontent.com/66519591/183286911-a1d70bb5-4cc1-4437-8d92-e21a41cc5b6e.JPG)
![_20220807_123754](https://user-images.githubusercontent.com/66519591/183286914-2cca1c33-1ad9-460d-ad7a-b9d6bca7e12a.JPG)

**Comment by Jean-BaptisteC** [comment]
Fixed in 3.0 version coming in september

**Comment by Altonss** [comment]
Thanks a lot!
