### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Rudloff** [Exodus-Privacy/exodus-android-app#2]
Hello,

Are there any plans to distribute this app on [F-Droid](https://f-droid.org/)?

**Comment by U039b** [comment]
For sure!! The application will be available on F-Droid.

**Comment by Rudloff** [comment]
Great!
I opened a ticket for this here: https://gitlab.com/fdroid/rfp/issues/526

**Comment by IzzySoft** [comment]
@U039b If you could attach an `.apk` to the `releases/` I could serve your app via [my repo](https://apt.izzysoft.de/fdroid/) until it gets listed at the F-Droid main repo (which will take a little while, F-Droid being "understaffed" as it is).
