### ISSUE TITLE
Download reports and trackers doesn't start

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#201]
### Issues:

- Device: Pixel 6
- OS: Android 13
- App version: 3.0.0 (with release optimizations enabled)

Stacktrace:
```
08-29 18:21:07.353  9704  9732 E ExodusUpdateService: Unable to fetch apps
08-29 18:21:07.353  9704  9732 E ExodusUpdateService: java.lang.NumberFormatException: For input string: ""
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at java.lang.Long.parseLong(Long.java:602)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at java.lang.Long.parseLong(Long.java:632)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at org.eu.exodus_privacy.exodusprivacy.ExodusUpdateService.s(Unknown Source:152)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at org.eu.exodus_privacy.exodusprivacy.ExodusUpdateService.i(Unknown Source:0)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at org.eu.exodus_privacy.exodusprivacy.ExodusUpdateService$b.u(Unknown Source:11)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at v3.a.j(Unknown Source:11)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at l4.w0.run(Unknown Source:88)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at kotlinx.coroutines.internal.k.run(Unknown Source:12)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at kotlinx.coroutines.scheduling.k.run(Unknown Source:2)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at kotlinx.coroutines.scheduling.a.M(Unknown Source:0)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at kotlinx.coroutines.scheduling.a$c.d(Unknown Source:14)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at kotlinx.coroutines.scheduling.a$c.n(Unknown Source:28)
08-29 18:21:07.353  9704  9732 E ExodusUpdateService:   at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
```
One variable expecting a Long type but getting String (maybe versionCode)

- After has fixed problems, enable release optimizations in buildTypes release:
```
minifyEnabled true
shrinkResources true
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```
- Create new buildTypes debug and add sames optimizations to improve quality of app and prevent problems.

**Comment by Jean-BaptisteC** [comment]
This line is origin of the problem https://github.com/Exodus-Privacy/exodus-android-app/blob/7b966b1bcbf7c84be332ec85314b34889b049a13/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/ExodusUpdateService.kt#L263

**Comment by Jean-BaptisteC** [comment]
I think your problem is different because this problem is fixed on 3.0.0 version.
What is it your OS on your smartphone ?
How do you have update Exodus application ?
Can you clear cache on settings and re-open Exodus app ?

**Comment by Altonss** [comment]
> I think your problem is different because this problem is fixed on 3.0.0 version.
The problem happened because of the latest 3.0.0 release on F-Droid.

> What is it your OS on your smartphone ? Graphene OS, Android 13

> How do you have update Exodus application ? Yes

> Can you clear cache on settings and re-open Exodus app ? Didn't solve the issue

**Comment by Jean-BaptisteC** [comment]
Thanks for feedback, i know the problem, we have changed API KEY management and in Fdroid when server build APK. Server doesn't have API KEY. We will try find solutions but for now, you can download APK on [Github](https://github.com/Exodus-Privacy/exodus-android-app/releases/tag/release-v3.0.0).

**Comment by Altonss** [comment]
Couldn't the API key simply be in the source code?
From what I heard over on https://github.com/johan12345/EVMap IIRC the key can easily be retrieved from the apk anyway...

**Comment by Altonss** [comment]
> Couldn't the API key simply be in the source code? From what I heard over on https://github.com/johan12345/EVMap IIRC the key can easily be retrieved from the apk anyway...

The keys are in clear text available here: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.vonforst.evmap.yml
Maybe this can help you :)

**Comment by Altonss** [comment]
@Jean-BaptisteC maybe this issue can be closed (if it was related to the F-Droid issue as it is solved now)?

**Comment by Jean-BaptisteC** [comment]
No this issue is not related to FDroid, we have problem of type of variables in own code.
And actually, if we enable optimizations during build -> when you launch, app crashed :(

**Comment by PatDyn** [comment]
R8, the android compiler, does some radical reduction of code when enabled.
This can lead to unexpected behavior, when not properly configured. Especially, when reflection is used (as okhttp3 does for example). 

We need to properly configure R8 (using proguard-rules.pro)
