### ISSUE TITLE
Improve how API KEY is stored in app

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#202]
API Key is stored in [app/build.gradle](https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/build.gradle).
This solution is not secure maybe find solution to improve how API KEY is stored in app.

Links:
- https://blog.kotlin-academy.com/how-to-secure-secrets-in-android-android-security-01-a345e97c82be
- https://www.codementor.io/blog/kotlin-apikeys-7o0g54qk5b

**Comment by outis151** [comment]
As mentioned in https://github.com/Exodus-Privacy/exodus-android-app/issues/207#issuecomment-1242904852 none of these methods will help you hide the api key... They might make it a bit more difficult only
