### ISSUE TITLE
Bug: too much scroll possible on trackers tab in app details

### ISSUE THREAD

**Issue by Altonss** [Exodus-Privacy/exodus-android-app#205]
When the trackers aren't loaded yet, I can scroll the trackers tab very far until all the screen becomes black. This shouldn't happen I think...

**Comment by Jean-BaptisteC** [comment]
Thanks for feedback, yes i know this bug, trackers tabs and permissions tabs have sames dimensions.
If reports have lot of permissions tab trackers take sames dimensions then permissions tab.

**Comment by Altonss** [comment]
Would there be a way to have 2 separate dimensions? :thinking: I don't know Kotlin at all, so I can't help on that one ^

**Comment by siva-subramaniam-v** [comment]
@Jean-BaptisteC I've looked at multiple solutions and all of them use a custom view that extends ViewPager and overrides the onMeasure() method.

Let me know if this solution sounds good or if you have any other suggestions.

**Comment by Jean-BaptisteC** [comment]
I'm really not an expert in Android dev, but i think it's good idea. When do you want call onMeasure each time user switch between tabs or only one time when users open AppDetailFragment ?

**Comment by siva-subramaniam-v** [comment]
onMeasure() is a method that is called to get the measurements of a view (a view is any UI element) in Android. The idea behind overriding the onMeasure() function is that we are providing our own measurement to Android.

In this case, we will provide the height of the child element (tracker fragment/permission fragment) so that the ViewPager's height will be the height of the current tab.

More about onMeasure on [stackoverflow](https://stackoverflow.com/a/12267248/17240756)

**Comment by Jean-BaptisteC** [comment]
Thanks for more explanation,  yes i think it's a good solution

**Comment by siva-subramaniam-v** [comment]
@Jean-BaptisteC Unfortunately, in the Exodus app ViewPager2 is used which is a final class that cannot be extended.

Therefore the solution mentioned above isn't possible.

I've tried multiple solutions for ViewPager2:

1. [stackoverflow.com/a/64235840](https://stackoverflow.com/a/64235840)
2. [stackoverflow.com/a/58632613/17240756](https://stackoverflow.com/a/58632613/17240756)
3. [stackoverflow.com/a/68691439/17240756](https://stackoverflow.com/a/68691439/17240756)

but none of them worked perfectly.

Resources:

1. [developer.android.com/guide/topics/ui/how-android-draws](https://developer.android.com/guide/topics/ui/how-android-draws)
2. [issuetracker.google.com/u/0/issues/143095219](https://issuetracker.google.com/u/0/issues/143095219)

I hope someone can make use of the linked resources and fix this bug in the future.

**Comment by Jean-BaptisteC** [comment]
Thanks for research, it's not a problem if this bug is not solved now 🙂
