### ISSUE TITLE
Idea.

### ISSUE THREAD

**Issue by ghost** [Exodus-Privacy/exodus-android-app#208]
you can make 1 appear where 2 appears.
![1](https://user-images.githubusercontent.com/113162918/189283284-58ca55e5-68ae-49e2-84e1-38a310e57e37.png)

vlc can be scanned through the app.
![2](https://user-images.githubusercontent.com/113162918/189281143-1f5aa2b2-b982-492e-b06a-fe37147fb9ad.jpg)

**Comment by Jean-BaptisteC** [comment]
Scan button is show on report only if app has been never scan on Exodus platform.
It's planned in the future to replace scan button by a floating button at the bottom of the screen to improve visibility.
It's not planned to add scan button on reports for apps already analysed.
I think it's better to analysed apps never analysed. I don't find interest to analysed each version of apps mostly if developpers has not added or removed trackers/permissions.

**Comment by Jean-BaptisteC** [comment]
Why, can you give me arguments ?
Why do you want we add this button on latest reports ?
