### ISSUE TITLE
Reimplement search bar

### ISSUE THREAD

**Issue by marwan-mustafa** [Exodus-Privacy/exodus-android-app#209]
It would be better if the app list had a search bar instead of just listing apps. 

In addition. I think it would be convenient if applications could be sorted by how many trackers they have.

**Comment by Jean-BaptisteC** [comment]
Hi @objestik
It's planned to add search and sort by features in 3.0.0 version.
These features are already on 2.0.0 version, but we have not enough time to develop this before 3.0.0.

**Comment by cchigo** [comment]
hi, can i work on this

**Comment by Jean-BaptisteC** [comment]
Yes :)

**Comment by Jean-BaptisteC** [comment]
@cchigo Some tips:

- Search bar already exists, she is just hide -> remove this line https://github.com/Exodus-Privacy/exodus-android-app/blob/77e9b3ce4c3417eacb0ffd7b6a2f116eeb87457c/app/src/main/res/menu/apps_menu.xml#L9
- Maybe update search icon with icon from [material symbols](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Asearch%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048)
- You can use this search bar or other like you want
- Implement search only on [AppFragment](https://github.com/Exodus-Privacy/exodus-android-app/tree/master/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/apps)
- Be careful about this https://github.com/Exodus-Privacy/exodus-android-app/issues/100 :)

**Comment by cchigo** [comment]
hello, thanks for the useful tips.

**Comment by cchigo** [comment]
I cant see the comments for the requested changes

**Comment by starry-shivam** [comment]
Hi! I was about to create a similar issue before I stumbled upon this. I can work on adding this if you want :)

**Comment by Jean-BaptisteC** [comment]
Yes, go
Don't ask to work on issue ;)
