### ISSUE TITLE
expose more details in Exodus 3.0

### ISSUE THREAD

**Issue by yoshimo** [Exodus-Privacy/exodus-android-app#224]
I liked the pre-3.0 design  more.
It is a lot more obvious  that  applications need a new scan and which versions  are compared  if you have a readable text block  instead of a tiny icon  that you need to hover  over.

Could we have this block  back, maybe optionally?
I'd keep running  the old,  ore visually pleasing edition but it doesn't get reports any longer  :)

**Comment by Jean-BaptisteC** [comment]
Thanks for feedback, we know, icons is not perfect
The real difficulty is show lot of informations without take a lot of place with material you 3.0 default padding is more important.

I can be you give some tips:
- X this icon is show when app has never analyzed and on report with have this button https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Apolicy%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048 which open exodus with handle app on field
- <> this icon is show when installed verion is different from analyzed version

**Comment by Jean-BaptisteC** [comment]
Hi @yoshimo, in the next version I re-implement a text block foreach app on main screen.
