### ISSUE TITLE
Remove white strips around the screen

### ISSUE THREAD

**Issue by Porkepix** [Exodus-Privacy/exodus-android-app#24]
To get a little bit more space and have a better presentation, it could be nice removing partly if not totally, white strips around the screen. Especially the ones on top and bottom of the screen.

**Comment by Schoumi** [comment]
margins has been  reduce during the release 1.0.4 and commit 9c619c21359ffcaab82a986c5ff9126f859951c2
Still open in case more user complaints about this.
