### ISSUE TITLE
Remove permission description

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#240]
Actually, foreach permissions on app, we show label and description.
Label is enough to understand permission and remove description can be improve performance on reports with a lot of permissions

- [x] Remove [expand](https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/model/ADPermissionsRVAdapter.kt)
- [x] Remove description in code
- [x] Fix padding between each permission (i have doing tests and some label are cropped)

**Comment by av-arvind77** [comment]
Hey @Jean-BaptisteC ,
I would like to work on this issue. Can you please assign this issue to me ?

**Comment by Jean-BaptisteC** [comment]
I have already create PR to fix this
