### ISSUE TITLE
Add floating button to update reports

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#241]
This feature improve accessibility in app to update reports, if we implement this floating button we shown only on My apps tab
Some designs:
<img src="https://user-images.githubusercontent.com/87148630/215268557-5ef1ba46-b8b0-49f1-b489-07ab56aca72f.png" height="200" />

<img src="https://user-images.githubusercontent.com/87148630/215268569-217871e7-ee83-4a8f-ab2d-ef7a7fc831e6.png" height="195" />
<img src="https://user-images.githubusercontent.com/87148630/215268622-114f3569-b276-40ee-b3ba-3d08b462d06f.png" height="200" />
For latest design, if we scroll at the bottom, text is hide

We can use this icon (used in notification during refresh) https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/src/main/res/drawable/ic_update.xml

**Comment by n1snt** [comment]
Is this any different than pull to refresh?
If not I cannot think of any situation where this would be needed because we already have pull to refresh.
