### ISSUE TITLE
Improve trackers and permissions chip

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#242]
Some users don't understand icon behind number in chip, i suggest to update this:

- [ ] Add trackers and permission text after number
- [ ] On all fragments
Some design:
<img src="https://user-images.githubusercontent.com/87148630/215269882-6839d786-5568-43b6-802c-c6aded400ad1.png" height="150" />
<img src="https://user-images.githubusercontent.com/87148630/215269905-59e07939-2df6-4c4d-a969-090e1a152604.png" height="200" />
<img src="https://user-images.githubusercontent.com/87148630/215269939-cd620c47-d39b-4b33-8cb3-2aa2b4ec782b.png" height="150" />

**Comment by n1snt** [comment]
Hey if no one is working on this I would love to have a try at this.

**Comment by Jean-BaptisteC** [comment]
Yes, no problem

**Comment by n1snt** [comment]
Hey, How about keeping both the icon & text?
Because it seems to look better than only text.
Example:
![image](https://github.com/Exodus-Privacy/exodus-android-app/assets/46300244/a7117454-c6b7-4826-9e0b-304ca95426e9)

**Comment by Jean-BaptisteC** [comment]
Try with apps with more 100 permissions

**Comment by n1snt** [comment]
![image](https://github.com/Exodus-Privacy/exodus-android-app/assets/46300244/a96312e2-75fd-4332-80cf-8cb8b0bd208f)
How about I move the tick chip below?

**Comment by Jean-BaptisteC** [comment]
Or move after title app ?
Be careful about with long name and long name version

**Comment by n1snt** [comment]
Looks like if we keep the icon on both we run into issues on smaller devices (Like a nexus 5)
![image](https://github.com/Exodus-Privacy/exodus-android-app/assets/46300244/2cc0f94b-09e8-4a2d-b519-75018bd3d82b)

**Comment by n1snt** [comment]
If I remove the icon & the padding from the start it can accommodate everything in one line without moving anything below. (On a Nexus 5)
![image](https://github.com/Exodus-Privacy/exodus-android-app/assets/46300244/33e19adf-7d62-4c97-8fb1-3fe99a066d0e)

**Comment by Jean-BaptisteC** [comment]
Loos good

**Comment by n1snt** [comment]
Hey, unfortunately, I was caught up in a few things.
I'll get back to creating a PR for this in a few days.
