### ISSUE TITLE
New logo design for the project

### ISSUE THREAD

**Issue by Arslanshn** [Exodus-Privacy/exodus-android-app#28]
Hi, I want to design a new logo for the project completely free...

**Comment by U039b** [comment]
Hi!!
Thank you!
Feel-free to share your ideas with us :-D

**Comment by Arslanshn** [comment]
https://drive.google.com/drive/folders/1I_VfueSuoIPCgkUZ17o_fBFzy_ZE5wCK?usp=sharing
hello I'm working on a sketch I hope you like it.

**Comment by Arslanshn** [comment]
Hello I wonder if the idea of ​​logo do you like it?

**Comment by U039b** [comment]
Hi! 
We will talk about the logo during our next member meeting on Sunday ;-)

**Comment by Arslanshn** [comment]
Hi, did you decide to use the logo?

**Comment by U039b** [comment]
Hi! 
You are sorry but we have decided to keep the actual logo. Your logo looks really nice but we cannot change our visual identity. We have tons of stickers with it, +1000 articles displaying it, ...

**Comment by Arslanshn** [comment]
Hi no problem.
