### ISSUE TITLE
Fix about section landscape mode.

### ISSUE THREAD

**Issue by n1snt** [Exodus-Privacy/exodus-android-app#282]
#### Issue:
When in the About section in landscape mode the text gets cut as only the bottom section with the links is scrollable.

#### How to replicate:
1. Launch the app
2. Go to the About section
3. Rotate the phone

#### Image for reference:
![image](https://github.com/Exodus-Privacy/exodus-android-app/assets/46300244/df06f1f2-5a04-4081-a3bd-b826ca6f0692)

_I would love to work on this if this gets approved as a valid issue._

**Comment by Jean-BaptisteC** [comment]
Do you want create new tablet layout with logo at the left and link at the right to fix problem ?

**Comment by n1snt** [comment]
I think making a tablet UI would be the appropriate solution here.
