### ISSUE TITLE
Implement methods in Utils to open link and ignore ActivityNotFoundException

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#286]
Actually in app, we open link without ignore crash ActivityNotFoundException.
I have added fix here https://github.com/Exodus-Privacy/exodus-android-app/pull/276/commits/a4755ccb96142c47c7f3e2ed32b54dd444ce5749 to ignore ActivityNotFoundException and don't generate crash when devices have not mail app or store app

I suggest to create 2 methods in utils:

- Method to open link in customTabsIntent and ignore ActivityNotFoundException  -> example here https://github.com/Exodus-Privacy/exodus-android-app/blob/a4755ccb96142c47c7f3e2ed32b54dd444ce5749/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt#L79 (this method is used to open each link in app)
- Method to open start activity and ActivityNotFoundException  -> example here https://github.com/Exodus-Privacy/exodus-android-app/blob/a4755ccb96142c47c7f3e2ed32b54dd444ce5749/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/about/AboutFragment.kt#L103 (this method was only used to open mail app with mail address)

**Comment by ZSank** [comment]
Hello Jean, I am looking for my first good contribution. So, it will great, if I can contribute to this issue. 
I am thinking of solving the issue by this approach. 
These are the two methods I created as mentioned in the original issue. 
Please let me know, in which file should I put these methods?

```
fun customTabIntentWithoutException(view: View, string: String) {
	try {
		customTabsIntent.launchUrl(
			view.context,
			Uri.parse(string)
		)
	} catch (e: ActivityNotFoundException) {
	}
}

fun startActivityWithoutException(intent: Intent) {
	try {
		startActivity(intent)
	} catch (e: ActivityNotFoundException) {
	}
}
```
Waiting for your feedback. Thank you.

**Comment by Jean-BaptisteC** [comment]
Code looks good, you can add methods in CommonExtensions.kt
Please wait, i want push PR #276 before because, i have doing somes changes about this

**Comment by ZSank** [comment]
Ok

**Comment by Jean-BaptisteC** [comment]
PR is merge, you can push your changes

Be careful here https://github.com/Exodus-Privacy/exodus-android-app/blob/f88d9427361dfde2be9f727ac22d7d419d5136cc/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/fragments/appdetail/AppDetailFragment.kt#L96 if users doesn't have app store, i start browser
Same here with settings https://github.com/Exodus-Privacy/exodus-android-app/blob/f88d9427361dfde2be9f727ac22d7d419d5136cc/app/src/main/java/org/eu/exodus_privacy/exodusprivacy/MainActivity.kt#L46
