### ISSUE TITLE
Do not scan at every enter in the app

### ISSUE THREAD

**Issue by Zykino** [Exodus-Privacy/exodus-android-app#29]
A scan once a day or on demand (Swipe the list to the bottom) should be enough.

**Comment by fabianski7** [comment]
@Zykino I guess this is fixed by https://github.com/Exodus-Privacy/exodus-android-app/pull/90?

**Comment by Zykino** [comment]
Just tested the new comportment. It is better. It does not remember if the app is clean from the recent app list (or I don’t know how this should be called). But at least if you do a session of back and forth in the settings/uninstall, check again this should be better now.
