### ISSUE TITLE
Fix linter error

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#300]
Latest version of ktlint cannot be update, because linter fail, because we use name package with underscore.
Two ways to fixed problem:
- Disable rule ktlint_standard_package-naming
- Update name package and namespace (replace `org.eu.exodus_privacy.exodusprivacy` by `org.eu.exodusprivacy.exodus`) we need to be sure it's comptatible with older version when users update app and be careful about git blame

**Comment by n1snt** [comment]
Instead of disabling the lint rule, we should treat the root cause & update the name package.

**Comment by Jean-BaptisteC** [comment]
Okay, but we need to be sure migration between older name package and new name package, maybe you can check how organic maps has doing to migrate name package

**Comment by n1snt** [comment]
This is the PR which migrated the package name in organicmaps. https://github.com/organicmaps/organicmaps/pull/3657
From my understanding:
- Created 2 commits
- First one renamed the package
- The second commit added a `.git-blame-ignore-revs` file to ignore the first commit.
