### ISSUE TITLE
Risk while installing Exodus from Fdroid 

### ISSUE THREAD

**Issue by AbhimanyuAryan** [Exodus-Privacy/exodus-android-app#312]
Got this notification 🔔
I am curious if everything is fine. I still installed it 🐞 

![Screenshot_2023-07-03-04-14-01-36_b5a5c5cb02ca09c784c5d88160e2ec24.jpg](https://github.com/Exodus-Privacy/exodus-android-app/assets/8083613/c433192f-ba7b-4927-8f67-deb7347521be)

**Comment by Jean-BaptisteC** [comment]
Google Play Protect analyze apps installed and in this case, Google Play doesn't recognize keystore used to sign app
Keystore are different between Fdroid and Google Play
It's a fake alert

**Comment by AbhimanyuAryan** [comment]
Thanks for the reply 🙏
