### ISSUE TITLE
App cant find any Apps, even if it should

### ISSUE THREAD

**Issue by beerisgood** [Exodus-Privacy/exodus-android-app#33]
I try the F-Droid Version and the Playstore Version but both dont show any Apps.
I have for example the "Super Backup App" App from Playstore (with Yalp) installed but Exodus doesnt show it.

I run LineageOS 15.1 (Android 8.1) under OnePlus 2 without GAPPS and use Aurora (Yalp Fork) for download & install Playstore apps

**Comment by Schoumi** [comment]
Duplicate #7 will be fixed in the next release.
