### ISSUE TITLE
Feature Request: Implement "Share To" option

### ISSUE THREAD

**Issue by snarkywolverine** [Exodus-Privacy/exodus-android-app#337]
Here's the scenario: I'm on my phone, looking for an app that will do <x>, and there are multiple choices available.  I'd like to find one that has only a few trackers. How can I go about this?

Since the Play Store has a "share to" option, it would be helpful to "Share To" the Exodus Privacy app, which can then pull up the most recent statistics (or generate a report if one hasn't been run).  This saves the user from having to copy/paste the URL, go to Exodus Privacy's website, and search again.

**Comment by Jean-BaptisteC** [comment]
In older version (2.0), this feature is available but it's not intuitive for users.
If you want to see trackers before downloading app from Play Store, you can use [Aurora Store](https://f-droid.org/fr/packages/com.aurora.store/)
