### ISSUE TITLE
app crash after initial applications scan

### ISSUE THREAD

**Issue by hobbes** [Exodus-Privacy/exodus-android-app#34]
Hello, 

when I start Exodus, it analyzes the installed apps, then crashes. If I try to restart it, I don't see a new apps scan, the crash is immediate. I'm on LineageOS 14.1.

Here is the relevant part of logcat:

09-03 20:11:45.889 17950 17950 D AndroidRuntime: Shutting down VM
09-03 20:11:45.891 17950 17950 E AndroidRuntime: FATAL EXCEPTION: main
09-03 20:11:45.891 17950 17950 E AndroidRuntime: Process: org.eu.exodus_privacy.exodusprivacy, PID: 17950
09-03 20:11:45.891 17950 17950 E AndroidRuntime: java.lang.IllegalArgumentException: the bind value at index 2 is null
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at org.eu.exodus_privacy.exodusprivacy.manager.DatabaseManager.getReportFor(DatabaseManager.java:196)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationListAdapter$ApplicationListViewHolder.setData(ApplicationListAdapter.java:153)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationListAdapter.onBindViewHolder(ApplicationListAdapter.java:91)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at org.eu.exodus_privacy.exodusprivacy.adapters.ApplicationListAdapter.onBindViewHolder(ApplicationListAdapter.java:45)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:729)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.View.layout(View.java:17641)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-03 20:11:45.891 17950 17950 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-03 20:11:45.893  2978  3724 W ActivityManager:   Force finishing activity org.eu.exodus_privacy.exodusprivacy/.MainActivity
09-03 20:11:45.906 17950 17950 I Process : Sending signal. PID: 17950 SIG: 9
09-03 20:11:45.913   505   505 E lowmemorykiller: Error writing /proc/17950/oom_score_adj; errno=22
09-03 20:11:45.915  2978  3158 W ActivityManager: Failed setting process group of 17950 to 1
09-03 20:11:45.915  2978  3158 W System.err: java.lang.IllegalArgumentException: Given thread 17970 does not exist
09-03 20:11:45.915  2978  3158 W System.err: 	at android.os.Process.setThreadPriority(Native Method)
09-03 20:11:45.916  2978  3158 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:20777)
09-03 20:11:45.916  2978  3158 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:21310)
09-03 20:11:45.916  2978  3158 W System.err: 	at com.android.server.am.BroadcastQueue.processCurBroadcastLocked(BroadcastQueue.java:274)
09-03 20:11:45.916  2978  3158 W System.err: 	at com.android.server.am.BroadcastQueue.processNextBroadcast(BroadcastQueue.java:1225)
09-03 20:11:45.916  2978  3158 W System.err: 	at com.android.server.am.BroadcastQueue$BroadcastHandler.handleMessage(BroadcastQueue.java:172)
09-03 20:11:45.916  2978  3158 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-03 20:11:45.916  2978  3158 W System.err: 	at android.os.Looper.loop(Looper.java:154)
09-03 20:11:45.916  2978  3158 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-03 20:11:45.916  2978  3158 W System.err: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)

09-03 20:11:45.957  2978  3559 W InputDispatcher: channel '8dca51f org.eu.exodus_privacy.exodusprivacy/org.eu.exodus_privacy.exodusprivacy.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
09-03 20:11:45.957  2978  3559 E InputDispatcher: channel '8dca51f org.eu.exodus_privacy.exodusprivacy/org.eu.exodus_privacy.exodusprivacy.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-03 20:11:45.958  2978 25442 D GraphicsStats: Buffer count: 11
09-03 20:11:45.960  2978 25442 I WindowManager: WIN DEATH: Window{8dca51f u0 org.eu.exodus_privacy.exodusprivacy/org.eu.exodus_privacy.exodusprivacy.MainActivity}
09-03 20:11:45.960  2978 25442 W InputDispatcher: Attempted to unregister already unregistered input channel '8dca51f org.eu.exodus_privacy.exodusprivacy/org.eu.exodus_privacy.exodusprivacy.MainActivity (server)'
09-03 20:11:45.964  2978  4596 I ActivityManager: Process org.eu.exodus_privacy.exodusprivacy (pid 17950) has died
09-03 20:11:45.964  2978  4596 D ActivityManager: cleanUpApplicationRecord -- 17950

Thanks,
-- 
Rémi

**Comment by tdelmas** [comment]
I have the same symptoms (crash after initial application scan) but the  my logcat tells a different story:

I see a few:

```
E/art: Throwing OutOfMemoryError "Failed to allocate a 24 byte allocation with 6 free bytes and 6B until OOM"
```

And then:

```

I/art: Clamp target GC heap from 143MB to 128MB
    Alloc concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.586ms total 320.281ms
I/art: WaitForGcToComplete blocked for 331.237ms for cause Alloc
E/art: Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 6 free bytes and 6B until OOM" (recursive case)
E/art: "main" prio=5 tid=1 Runnable
      | group="main" sCount=0 dsCount=0 obj=0x77645f48 self=0xb4e07800
      | sysTid=17544 nice=0 cgrp=apps sched=0/0 handle=0xb6fa0ec8
      | state=R schedstat=( 0 0 0 ) utm=637 stm=32 core=1 HZ=100
      | stack=0xbe15c000-0xbe15e000 stackSize=8MB
      | held mutexes= "mutator lock"(shared held)
        at java.lang.Float.valueOf(Float.java:403)
        at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.getAnimatedValue(PropertyValuesHolder.java:1268)
        at android.animation.ValueAnimator.getAnimatedValue(ValueAnimator.java:760)
        at android.support.v4.widget.CircularProgressDrawable$1.onAnimationUpdate(CircularProgressDrawable.java:571)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1283)
        at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1207)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1248)
        at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:659)
        at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
        at android.view.Choreographer.doCallbacks(Choreographer.java:590)
        at android.view.Choreographer.doFrame(Choreographer.java:559)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5951)
        at java.lang.reflect.Method.invoke!(Native method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
I/art: Clamp target GC heap from 143MB to 128MB
    Alloc concurrent mark sweep GC freed 0(0B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.556ms total 358.734ms
I/art: WaitForGcToComplete blocked for 671.752ms for cause Alloc
E/art: Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 6 free bytes and 6B until OOM" (recursive case)
    "Thread-1041" prio=5 tid=14 Runnable
      | group="main" sCount=0 dsCount=0 obj=0x132090f0 self=0xb4e0ac00
      | sysTid=17619 nice=0 cgrp=apps sched=0/0 handle=0xaf256e80
      | state=R schedstat=( 0 0 0 ) utm=1049 stm=109 core=0 HZ=100
      | stack=0x9b818000-0x9b81a000 stackSize=1036KB
      | held mutexes= "mutator lock"(shared held)
        at java.util.Arrays.copyOfRange(Arrays.java:2701)
        at java.lang.String.<init>(String.java:421)
        at org.json.JSONTokener.nextString(JSONTokener.java:210)
        at org.json.JSONTokener.nextValue(JSONTokener.java:107)
        at org.json.JSONTokener.readObject(JSONTokener.java:362)
        at org.json.JSONTokener.nextValue(JSONTokener.java:100)
        at org.json.JSONTokener.readArray(JSONTokener.java:430)
        at org.json.JSONTokener.nextValue(JSONTokener.java:103)
        at org.json.JSONTokener.readObject(JSONTokener.java:385)
        at org.json.JSONTokener.nextValue(JSONTokener.java:100)
        at org.json.JSONObject.<init>(JSONObject.java:156)
        at org.json.JSONObject.<init>(JSONObject.java:173)
        at org.eu.exodus_privacy.exodusprivacy.manager.NetworkManager$NetworkProcessingThread.makeDataRequest(NetworkManager.java:165)
        at org.eu.exodus_privacy.exodusprivacy.manager.NetworkManager$NetworkProcessingThread.getApplications(NetworkManager.java:221)
        at org.eu.exodus_privacy.exodusprivacy.manager.NetworkManager$NetworkProcessingThread.run(NetworkManager.java:125)
I/art: Clamp target GC heap from 143MB to 128MB
    Alloc concurrent mark sweep GC freed 9(608B) AllocSpace objects, 0(0B) LOS objects, 0% free, 127MB/128MB, paused 1.495ms total 309.661ms
I/art: WaitForGcToComplete blocked for 636.138ms for cause Alloc
I/art: WaitForGcToComplete blocked for 298.553ms for cause Alloc
D/AndroidRuntime: Shutting down VM
I/Process: Sending signal. PID: 17544 SIG: 9
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

```

**Comment by Schoumi** [comment]
hum miss this one. Is it still there in the version release last week?

**Comment by hobbes** [comment]
just tested 1.2.0, no crash anymore. Thanks :-)
