### ISSUE TITLE
Improve transitions in app

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#346]
Actually, we used only `MaterialFadeThrough` transition.
We can use other transitions for better animation in app
https://m3.material.io/styles/motion/overview
https://github.com/material-components/material-components-android/blob/master/docs/theming/Motion.md

We can also use animations to hide bottom bar

**Comment by Jean-BaptisteC** [comment]
Yes, feel free open a PR if you want

**Comment by rohit9625** [comment]
Sure : )

**Comment by rohit9625** [comment]
I have a question. Where we need to add animations?

**Comment by Jean-BaptisteC** [comment]
The bottom bar when you go to another fragment where the bottom bar is hidden
And basic animation between two fragment can be improve with better animations

**Comment by rohit9625** [comment]
Yeah, right I didn't noticed before. Thank you :)
