### ISSUE TITLE
Improve performance of recyclerview in app

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#386]
Somes crashes in app are related by loading of recyclerview too long (permissions recyclerview and app recyclerview)
We need to find a solution to reduce loading of view to improve start app loading and when user consult a app report

**Comment by connyduck** [comment]
I ran the app through the profiler, I couldn't find any performance problems in RecyclerViews.
But when switching between items in the main bottom navigation, Fragments (AppsFragment, TrackersFragment and AboutFragment) are recreated everytime. It even lags noticeably on my device. I have no idea how to fix that with Jetpack Navigation though.

**Comment by connyduck** [comment]
Could you maybe share these crash reports you have?
