### ISSUE TITLE
On Exodus 3.2.1, for almost all apps Exodus tells "Application not analyzed" instead of showing number of trackers

### ISSUE THREAD

**Issue by Valeryan24** [Exodus-Privacy/exodus-android-app#389]
Hi, thanks a lot for your great work on Exodus. I just updated to the last version 3.2.1 on FDroid.

But with this version, for almost all applications (except a few exceptions like Discord, Amaze, Accubattery), after having refreshed the reports, it only shows the "?" icon with a message "This app has not been yet analyzed by Exodus Privacy" (please see the joined screenshots, in French), instead of trackers number. Same if I click on an app to get more details.

Authorizations number and list are OK.

I have the bug on Samsung Galaxy S22+ (Android 14) and S10+ (Android 12), both on FDroid 3.2.1 version.

![Exodus-321-01](https://github.com/Exodus-Privacy/exodus-android-app/assets/1119619/d06c1e16-ba68-4595-a030-57a8db3de7a9)
![Exodus-321-02](https://github.com/Exodus-Privacy/exodus-android-app/assets/1119619/d242a6b1-4a32-4047-bb14-f05e4c8d4e25)

**Comment by Valeryan24** [comment]
I uninstalled FDroid version and tried the apk from Github, same issue : not all apps, not the same ones for which trackers number works, but for most of them, only a "?" instead of trackers count…

**Comment by Jean-BaptisteC** [comment]
Thanks for the feedback, In the last version we broke logic to get API KEY, we tried to fix the problem quickly.
