### ISSUE TITLE
Please add to the description what the permissions are used for

### ISSUE THREAD

**Issue by IzzySoft** [Exodus-Privacy/exodus-android-app#4]
It might be partly obvious, but being explicit would be much preferred – as there might be misunderstandings: Are the network permissions used for …

* retrieving definitions of known trackers from some server or
* transmitting app information to some server for "remote evaluation"?

Not everybody is capable of extracting that from the source code :wink:

**Comment by matlink** [comment]
Nothing is done client-side. All the reports are fetched from exodus servers.

**Comment by IzzySoft** [comment]
@matlink if that really is the case, the term "privacy" IMHO is a bit misleading. To me, privacy means my data stay with me – and are *not* uploaded somewhere. That definitions must be downloaded then would be OK (can't work otherwise).

**Comment by Schoumi** [comment]
The network permission is here to retrieve trackers and reports from Exodus API.
The access network state permission is here to know if the app can make api calls or it's not useful because you are out of any network.

Where would you have this description?

**Comment by IzzySoft** [comment]
In the app description on F-Droid and Playstore.

(apologies for the late reply; I had a server hardware crash at end of May which got fixed only in the second week of April, so I missed the notification).

> The network permission is here to retrieve trackers and reports from Exodus API.

That means it's API calls, i.e. at least the package name and version will need to be submitted to your server in order to obtain the details. In that case it'd also be good to have some note that you don't store that information (the tin foil of some people is much thicker than mine :wink:)

**Comment by simpnu** [comment]
I agree with @IzzySoft here that it would be great to have these simple descriptions in the Playstore/F-Droid app page.

**Comment by pnu-s** [comment]
I can confirm that this is included in our next version.
