### ISSUE TITLE
Add app license to About page

### ISSUE THREAD

**Issue by inson1** [Exodus-Privacy/exodus-android-app#402]
I think its important information

**Comment by inson1** [comment]
license of exodus app, that is for user more important imo

**Comment by inson1** [comment]
but maybe why not both? but separately

**Comment by Jean-BaptisteC** [comment]
We have already a link to Github and license is on Github, is not enough?
did you have see in other mobile app?

**Comment by inson1** [comment]
yes some apps have it
its nice when its also in about page, like I said I think that is important information
you have there also privacy policy, that is also on github (only link, but that doesnt matter)

**Comment by inson1** [comment]
@inson1 I know I meant in the app
