### ISSUE TITLE
Create custom screenshots with Espresso

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#405]

**Comment by Ammar-Ishfaq** [comment]
Can you provide additional details or expand on that further?

**Comment by Jean-BaptisteC** [comment]
Yes
I want to automate creation of screenshots published on stores.
Actually, I doing screenshots manually on phone and tablet in english and french it's take a lot of time and it's not easy to do screenshots with custom data.
I have see it's possible to do screenshots with espresso.
https://proandroiddev.com/automatic-screenshot-testing-for-all-your-compose-previews-6add202fecc7
