### ISSUE TITLE
Replace relative layout with constraint layout

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#409]
To build a view with relative layout Android doing two measure. To improve performance of app we can use constraint layout.
https://github.com/Exodus-Privacy/exodus-android-app/blob/master/app/src/main/res/layout/recycler_view_tracker_item.xml

**Comment by hegleB** [comment]
Hi, I can this issue be assigned to me?

**Comment by hegleB** [comment]
Hi, I can this issue be assigned to me?

**Comment by Jean-BaptisteC** [comment]
Go
