### ISSUE TITLE
Add github link to the app description

### ISSUE THREAD

**Issue by simpnu** [Exodus-Privacy/exodus-android-app#41]
I think it would make sense to add a link to this repository on the application description (on Google Play Store and F-droid). This would:
- show that the app is free and open source
- allow people to jump right to the code if they want to
- allow people to create issues easily

As always, happy to discuss/debate about this :)

**Comment by Schoumi** [comment]
in f-droid each app always have link to repository and issue tracker.

I will add it in google play.

**Comment by simpnu** [comment]
As this was done, I'm closing this, thanks @Schoumi :)
