### ISSUE TITLE
Tracker report for SD Maid is incorrect.

### ISSUE THREAD

**Issue by eddieofny** [Exodus-Privacy/exodus-android-app#411]
Exodus reports SD Maid as having 0 trackers, but using PCAPDroid, I noticed that SD Maid was making connections to Google Firebase.

Screenshots:
![Screenshot_2024-02-29-11-54-19](https://github.com/Exodus-Privacy/exodus-android-app/assets/98845254/70fc8e2a-bee3-488c-862b-f3424e5ad648)
![Screenshot_2024-02-24-21-47-53_1_1](https://github.com/Exodus-Privacy/exodus-android-app/assets/98845254/e23c1569-71bb-49e4-be1c-289e941460d8)

**Comment by Jean-BaptisteC** [comment]
App can send data without using Google Firebase library :(
And we cannot detect this case.

**Comment by eddieofny** [comment]
You learn something new everyday, I guess. Thanks for looking into it!
