### ISSUE TITLE
Check tracker domain list reachability

### ISSUE THREAD

**Issue by kisst** [Exodus-Privacy/exodus-android-app#414]
In some cases more privacy friendly options are not available hence the data that tracker is in the app isn't that useful , however as the tracker address are collected and known already it could be used for connection checking.
It is reasonable to presume that privacy conscious users who use the application have some kind of preventive control in place to make those tracker code snippets in the application code useless , either on DNS or just TCP level somewhere .
I think it would be a great addition for the application to show which trackers are reachable and which ones are blocked .

**Comment by Jean-BaptisteC** [comment]
I'm not sure users want to send IP to a server of trackers. And we have just network signature is not enough to build request.

**Comment by kisst** [comment]
If they have the trackers already present in one of their installed applications then it's nothing new , and getting a confirmation that it's harmless because unreachable would be useful .
