### ISSUE TITLE
Drop support of Android 5

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#435]
Exodus app supports all versions from Android 5 to Android 14. (Our app works on devices that are more than 10 years old).
With new Android versions each year, Google adds new constraints and asks developers to increase targetSDK version to improve the security of apps.

- FDroid has dropped support of Android 5 in 2023 on their app which reduces the ability to install our app on old devices)
- On Google Play, we have 30 users on Android 5.0 and 43 users on Android 5.1 (we have 23000 users on all Android versions).

A new version of Android was coming this summer with maybe new constraints to able to publish on Google Play Store.
Of course old versions continue to work on Android 5

I suggest dropping support of Android 5 before this summer. It's better to do a release only to drop support of Android version.

**Comment by Jean-BaptisteC** [comment]
@jfoucry WDYT?

**Comment by codeurimpulsif** [comment]
I'm ok with this, let just drop it and make our app work with Android 6+
