### ISSUE TITLE
Option to uninstall app

### ISSUE THREAD

**Issue by lenke182** [Exodus-Privacy/exodus-android-app#44]
The impact your app would be greater if someone could directly uninstall an app after seeing how many tracker etc. are implemented. I imagine a button in the appbar on the right with an intent to ACTION_DELETE.

**Comment by simpnu** [comment]
IIRC we discussed this internally and said that maybe adding a button that links to the application settings page in Android would make more sense as it would allow the user to:
- remove some permissions
- delete the application

I personally prefer this solution as this is not an incitement for the user to delete the app.

**Comment by lenke182** [comment]
This was implemented in 1f97fe76885bf2242b736e853ed210bce6e70d3d.
Closing this.
