### ISSUE TITLE
"This app hasn't been analyzed by Exodus Privacy yet."

### ISSUE THREAD

**Issue by InfamousUser** [Exodus-Privacy/exodus-android-app#49]
I get "This app hasn't been analyzed by Exodus Privacy yet." on every single app in the app.

**Comment by Schoumi** [comment]
Can you find some of them here: https://reports.exodus-privacy.eu.org/fr/
If yes it's a bug and I need many more information to help you, if not, you can ask for analyse here (only work for free apps): https://reports.exodus-privacy.eu.org/fr/analysis/submit/

**Comment by Schoumi** [comment]
@InfamousUser bug still there in the latest version? If yes could you look to my previous message. We'll try to fix this.

**Comment by InfamousUser** [comment]
I stopped using the app, didn't find a solution. Sorry.
