### ISSUE TITLE
No "filter" option on Tablet and forced 2 column layout

### ISSUE THREAD

**Issue by 825i** [Exodus-Privacy/exodus-android-app#493]
On mobile there is an extremely useful option to filter/sort by the amount of trackers. Showing apps with the most amount of trackers first.

On tablet this option does not exist anywhere in the UI.
It merely displays apps in a very busy "2 column" layout with no option for single column. 

Could we please have the option to filter/sort by trackers and display everything in a single column.

**Comment by Jean-BaptisteC** [comment]
Nice catch
