### ISSUE TITLE
Add total number of trackers in the applications of the smartphone

### ISSUE THREAD

**Issue by RAMAR-RAR** [Exodus-Privacy/exodus-android-app#50]
Add an area where is written the total of trackers installed on the applications in the smartphone

**Comment by Mineroboter** [comment]
A general privacy score would also be helpful. And a list of trackers (without duplicates) which have access to the phone.

**Comment by simpnu** [comment]
I don't think so we can provide a "privacy" score because there is no objective rating system.
The total number of trackers - and the list of trackers present on the phone - sounds like a new feature to me.

**Comment by Jean-BaptisteC** [comment]
List of trackers is already on app.
Maybe add number of trackers on the bottom of list of trackers
