### ISSUE TITLE
The number of trackers don't appear

### ISSUE THREAD

**Issue by MeTaLPoU** [Exodus-Privacy/exodus-android-app#56]
We tried to install the application yesterday on a Huawei phone, the number of trackers don't appear : 
![Screenshot_2019-06-20-14-18-32](https://user-images.githubusercontent.com/37960027/59951721-102fcd80-947a-11e9-9b98-7f6d0a5e305d.jpeg)

**Comment by Franck78** [comment]
My phone runs Android 4.4.4 
Xiaomi MI3

I'm pretty sure it's related to https. A tcpdump from my phone to 217.70.189.62 shows failed attempts  to establish the link

TLSv1.0 Client Hello
TLSv1.0 Fatal Protocol version
SSLv3.0 Client Hello
SSLv3.0 Fatal Protocol version

I'm not skilled enough to determine if this is applicable on my android flavor (chineese) :

https://stackoverflow.com/questions/45877125/enable-tls-1-2-in-android-4-4

TLSV1.2 can be (or must be ?) enabled on Kitekat.

Can you add this ?

Or build a debug app for me to test ?

Franck

**Comment by Jean-BaptisteC** [comment]
Can you try with latest version ? (Exodus_2.2.0)

**Comment by Franck78** [comment]
I'd like if it were downloadable from the 'normal' google store. But it is not. It doesn't exist!, A search for Exodus Privacy returns tons of crap.

Even this direct link on your github is 404.....

https://play.google.com/store/apps/details?id=org.eu.exodus_privacy.exodusprivacy

**Comment by Jean-BaptisteC** [comment]
Yes we know, we republish app on google play store soon
Exodus 2.2.0 is already available on [Fdroid](https://f-droid.org/fr/packages/org.eu.exodus_privacy.exodusprivacy/)

**Comment by Franck78** [comment]
Nothing changed with 2.2.0

(toujours le meme message, appli par encore analysée)

F

**Comment by Jean-BaptisteC** [comment]
Do you use the same smartphone with Android 4.4
"This app hasn\'t been analysed by Exodus Privacy yet." is show on each app on list ?
Can you pull to refresh in My apps and Trackers tab.
Do you use saver data mode on your smartphone ?

**Comment by Franck78** [comment]
* Do you use the same smartphone with Android 4.4
yes

* "This app hasn't been analysed by Exodus Privacy yet." is show on each app on list ?
yes

* Can you pull to refresh in My apps and Trackers tab.
yes, no change

Do you use saver data mode on your smartphone ?
?? connait pas !

As said previously:

I'm pretty sure it's related to https. A tcpdump from my phone to 217.70.189.62 shows failed attempts to establish the link

TLSv1.0 Client Hello
TLSv1.0 Fatal Protocol version
SSLv3.0 Client Hello
SSLv3.0 Fatal Protocol version

any answer on that topic (SSL/TLS) ?

**Comment by Jean-BaptisteC** [comment]
Use retrofit on Kotlin rewrite to support TLS1.2

**Comment by Jean-BaptisteC** [comment]
@theimpulson New app support TLS 1.2 with retrofit ?
