### ISSUE TITLE
install fail on F-droid

### ISSUE THREAD

**Issue by MeTaLPoU** [Exodus-Privacy/exodus-android-app#59]
![signal-attachment](https://user-images.githubusercontent.com/37960027/63859924-87b53800-c9a8-11e9-85fe-42f53ce12a3d.jpeg)
On a moto G5, the install on F-droid doesn't work.

**Comment by MrMagne** [comment]
As this was with my phone, please ping if I can provide some help.
And to be more precise, the installation is working from the play store, but fails with f-droid (after uninstalling the one from play-store off course)

**Comment by Schoumi** [comment]
Hum weird and i don't know what i can do to help you with this. The only way i can have more information is to make the installation with command line tools to have the real error message behind this. if you're on linux and have some skills with Command Line Interface, i can drives you to be able to have this.

As the installation is not on our hand, it's not one of our bug but still interesting to see what's going on.

**Comment by MrMagne** [comment]
I can run some command line on linux, no problem, finding the time to do so will be more problematic ;)
Tell me what you want me to run, and I'll try when I have the time.

**Comment by Schoumi** [comment]
can you tell me what android version your phone is running? LineageOS or Stock Rom?

**Comment by MrMagne** [comment]
stock ROM 8.1.0 (OPPS28.85-13-6)
I didn't try previous versions, do you have a link for an apk ?
Are the apk different between play store and f-droid ? because if they are not different that means the problem comes from the f-droid install method not from the apk, so testing a standalone apk might not be relevant...

**Comment by stom79** [comment]
My two cents https://framapiaf.org/@fedilab/102722504955370914

**Comment by stom79** [comment]
@Schoumi That's not the first time that Google Play Protect conflicts with Exodus apk from FDroid. This is of course a false positive (The same code is running without problems on Google Play).
It's maybe time to appeal to remove definitively this bug (if not yet done)?

The link is here:
https://support.google.com/googleplay/android-developer/contact/protectappeals?hl=en

**Comment by MrMagne** [comment]
I confirm it comes from play protect, when disabling it I'm able to install from F-Droid

**Comment by Schoumi** [comment]
i have made appeals fourth time since i first publish the app. 3 times they were unable to download the apk because the piece of code that download it is a piece of crap! once it work and have no answer of the appeal. I'm very tired of them!!!
