### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by tdelmas** [Exodus-Privacy/exodus-android-app#6]
Version 1.0 downloaded from https://seahub.0x39b.fr/f/38a160dfa0/?dl=1 as said in https://news.exodus-privacy.eu.org/

Android 5.0.1, Samsung S4 (with most preinstalled apps disabled, including chrome)

**Comment by tdelmas** [comment]
The relevant log:

D/AndroidRuntime(14508): Shutting down VM
E/AndroidRuntime(14508): FATAL EXCEPTION: main
E/AndroidRuntime(14508): Process: org.eu.exodus_privacy.exodusprivacy, PID: 14508
E/AndroidRuntime(14508): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.eu.exodus_privacy.exodusprivacy/org.eu.exodus_privacy.exodusprivacy.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.PackageManager.getInstalledPackages(int)' on a null object reference
E/AndroidRuntime(14508):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2702)
E/AndroidRuntime(14508):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
E/AndroidRuntime(14508):        at android.app.ActivityThread.access$900(ActivityThread.java:177)
E/AndroidRuntime(14508):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1449)
E/AndroidRuntime(14508):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(14508):        at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(14508):        at android.app.ActivityThread.main(ActivityThread.java:5951)
E/AndroidRuntime(14508):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14508):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(14508):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
E/AndroidRuntime(14508):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
E/AndroidRuntime(14508): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List android.content.pm.PackageManager.getInstalledPackages(int)' on a null object reference
E/AndroidRuntime(14508):        at org.eu.exodus_privacy.exodusprivacy.fragments.AppListFragment.startRefresh(AppListFragment.java:111)
E/AndroidRuntime(14508):        at org.eu.exodus_privacy.exodusprivacy.fragments.AppListFragment.onActivityCreated(AppListFragment.java:79)
E/AndroidRuntime(14508):        at android.app.Fragment.performActivityCreated(Fragment.java:2122)
E/AndroidRuntime(14508):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
E/AndroidRuntime(14508):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
E/AndroidRuntime(14508):        at android.app.BackStackRecord.run(BackStackRecord.java:833)
E/AndroidRuntime(14508):        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
E/AndroidRuntime(14508):        at android.app.Activity.performStart(Activity.java:6328)
E/AndroidRuntime(14508):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
E/AndroidRuntime(14508):        ... 10 more
V/ApplicationPolicy(16382): isApplicationStateBlocked userId 0 pkgname org.eu.exodus_privacy.exodusprivacy

**Comment by tdelmas** [comment]
Note: the version posted on the forum https://forum.exodus-privacy.eu.org/topic/7/nouvelle-version-beta-de-l-application-android still crash

**Comment by Schoumi** [comment]
Should have been fixed by: https://github.com/Exodus-Privacy/exodus-android-app/commit/3fceca295e80fd4edd80c54ab22b946bc2ea5eaa

An official release will be published very soon on google play. Tell me if with this version you still have the crash.

**Comment by Schoumi** [comment]
The app is on the playstore, you van try it :)

**Comment by tdelmas** [comment]
I confirm that the bug is fixed for the playstore version, thanks!
