### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by leela52452** [Exodus-Privacy/exodus-android-app#62]
can you please add changelog.
what is [CHANGELOG](https://en.m.wikipedia.org/wiki/Changelog) ?

**Comment by Jean-BaptisteC** [comment]
You can see changelog on apps store or in this [directory](https://github.com/Exodus-Privacy/exodus-android-app/tree/master/fastlane/metadata/android/en-US/changelogs).
Changelog is a file with changes from the lastest version on app.
