### ISSUE TITLE
(Request) upload scan button

### ISSUE THREAD

**Issue by 3xploiton3** [Exodus-Privacy/exodus-android-app#68]
Request for add upload (scanning) button or automatically scan

![](https://i.imgur.com/8lvLxl8.jpg)

**Comment by yoshimo** [comment]
if we had a serverside "last scan attempt" db entry to avoid overloading the system, it would be cool if the app could schedule scans for unknown apps and versions  on manual request and on startup.
https://github.com/Exodus-Privacy/exodus/pull/418 makes this a little bit easier now as we can check and mark apps that should be excluded from scanning

**Comment by pnu-s** [comment]
Duplicates https://github.com/Exodus-Privacy/exodus-android-app/issues/8
