### ISSUE TITLE
Only one app displayed

### ISSUE THREAD

**Issue by Rudloff** [Exodus-Privacy/exodus-android-app#7]
Hello,

I have several apps installed on my phone, from both F-Droid and Yalp Store (and several of them have Exodus reports), but Exodus 1.0.3 only displays one app.
If I refresh the list, it displays "Processing Applications: x/40" but does not add more app.

Am I missing something?

**Comment by matlink** [comment]
What's the version of your android?

**Comment by Rudloff** [comment]
I'm using Android 6.0.1 (without Play Services).

**Comment by Schoumi** [comment]
Only app identified as installed by the playstore are displayed. Yalp Store and F-Droid apps use the system to install apps and can't be easily identified as source. Exodus actually only test app from the playstore and even if yalp download app from it, i don't want to show false information because i don't know where the app is from.

**Comment by Schoumi** [comment]
hum sure about that? On my phone installer for f-droid is the same as yalp last time I checked
I'll try to look at this on yalp if it's easy to add in there.

**Comment by Rudloff** [comment]
I can confirm I see several apps installed by F-Droid when I run `pm list packages -i`:
```
package:com.amaze.filemanager  installer=org.fdroid.fdroid
```

It seems they set the installer name manually here: https://gitlab.com/fdroid/fdroidclient/blob/master/app/src/main/java/org/fdroid/fdroid/compat/PackageManagerCompat.java#L38

**Comment by Schoumi** [comment]
Seems not be done on all device. Do you have installed the fdroid privileged extension or activate an option somewhere in F-Droid? Seems not be only available for rooted device, that's weird.

**Comment by Rudloff** [comment]
I do have the privileged extension included in my ROM (Fairphone Open). It is disabled in F-Droid's preferences (so it still uses the OS installer) but maybe it still has an effect.

**Comment by matlink** [comment]
YalpStore is able to retrieve apps which are not installed with Play Store (via adb or Fdroid) even if it has not root privileges.

**Comment by Rudloff** [comment]
@Schoumi I tested on another device (Android 4.2.4 without F-Droid privileged extension) and I also have `installer=org.fdroid.fdroid`. I'm still not sure why you don't :disappointed:

**Comment by beerisgood** [comment]
1e65884 say it's fixed, but where is the binary file?
