### ISSUE TITLE
Sort apps by trackers count

### ISSUE THREAD

**Issue by orangemango** [Exodus-Privacy/exodus-android-app#70]
Adding the ability to sort apps by their trackers count or as default would helps to identify quickly wich apps needs inspection / replacement.

**Comment by PinkDev1** [comment]
@Schoumi, any progress on this?

**Comment by Schoumi** [comment]
I'm on a rework on some part that affect app display. I hope to release this soon and add this will be very easy. Sorry for the delay.

**Comment by pnu-s** [comment]
Fixed by #90
