### ISSUE TITLE
Add donation link to app

### ISSUE THREAD

**Issue by orangemango** [Exodus-Privacy/exodus-android-app#71]
I know you accept donations, and maybe most of your users comes from the Android app so I would make sense to let Android users know they can donate.

**Comment by stom79** [comment]
That needs a dedicated flavor for Fdroid. Be aware that Google removes apps that doesn't use their billing system even for donations.

**Comment by Jean-BaptisteC** [comment]
Google don't accept links in app to donate without use fonction on Google Play Store.
Users can be found links to donate on [Website](https://exodus-privacy.eu.org/fr/page/contribute/) or on [Github](https://github.com/Exodus-Privacy/exodus).
@pnu-s maybe add Funding.yml on [exodus-android-app](https://github.com/Exodus-Privacy/exodus-android-app) ?

**Comment by pnu-s** [comment]
@Jean-BaptisteC Sure, we have already done that for other repositories, we can do it for this one too!
