### ISSUE TITLE
What happens when an app is removed from the Play store?

### ISSUE THREAD

**Issue by snarkywolverine** [Exodus-Privacy/exodus-android-app#72]
In another issue thread, I thought I saw that Exodus only tracks apps that were installed via the Google Play Store.

Is there a way to show to the user that an app has since been removed from the Play store?  I keep seeing news articles about malicious apps that have been removed for whatever reason... but I haven't found a way to check and see if any of my installed apps have been removed.

Is that something this app could visualize?

**Comment by Schoumi** [comment]
Hi, no, we don't know when Google play store remove an app. We only have the source of the installation or signatures of it, that let us know the source on the phone. If an app is removed and still on your phone, we don't know.

if it's malicious and google removed it, it should have removed it on your phone too if i'm correct. 

I don't know if we could do something about it if it's note the case. For that we should know that google has removed it and i don't know if there somewhere such information.

I'll keep that in mind.

**Comment by pnu-s** [comment]
That's an interesting topic, it's also something we could track directly on exodus because we have the issue when counterfeit apps are removed from the Play Store but still on exodus

**Comment by Jean-BaptisteC** [comment]
The topic is compliquated because we have not enough informations to determine if app:
- Is delete by Google
- Is delete by developpers
- Is suspended by Google
- Is app is only available for some smartphones

**Comment by Jean-BaptisteC** [comment]
- I'm talking "tracking on exodus" directly in reports, this information is not enough trusted.
For example if developper remove application temporary and we add information on reports and after developper enable application on store, information on report is wrong.

- And for your solution we have not idea why app page on store is not available. And send request foreach app installed is not efficient.
