### ISSUE TITLE
Translations not in 2.0.0

### ISSUE THREAD

**Issue by Schoumi** [Exodus-Privacy/exodus-android-app#73]
Version 2.0.0 don't embeded some translations due to uncomplete support.
Exodus will have a plateform to centralize all translation and work on it to help our awesome translator to be as update as they can on new translation to avoid this in the futur.

**Comment by simpnu** [comment]
We can now create the project with the "Exodus Privacy" user on Crowdin so that all projects are available under the same URL: https://crowdin.com/profile/exodus-privacy

**Comment by Schoumi** [comment]
ping @jordimas @BoFFire @iramaro @solokot @czekaj @unbranched 
I've pinged you because you have done some amazing work on translation of this app and we have centralized what you've done on Crodwin. https://crowdin.com/project/exodus-android-app for the app itself and in general on what we have to translate you can check here: https://crowdin.com/profile/exodus-privacy. 

If you want to continue to contribute to translation of the app you could do there and be able to see change when I do some in a better way.

If you don't it's not a problem, thank you for what you've already done.
I promise not to ping you again for that topic :)

I plan a publication on saturday but no pressure i'll publish new translation regularly after that if we have new ones. :)
Thanks

**Comment by jordimas** [comment]
Done. Thanks for the heads up

**Comment by jordimas** [comment]
Has the new version been published? Thanks

**Comment by Schoumi** [comment]
it's on it's way since last night.

**Comment by Schoumi** [comment]
Some old translation missing but  for now it would be on crowdin. This issue is no longer relevant.
