### ISSUE TITLE
Encoding troubles with certain symbols

### ISSUE THREAD

**Issue by yoshimo** [Exodus-Privacy/exodus-android-app#74]
Some people like to use quotes in their version names
for example the monerujo app  ( com.m2049r.xmrwallet )
As long as website and exodus app have this representation:

`Version: 1.11.5 &apos;Chernushka&apos;`

The scan results will always tell you: this version hasn't been scanned.

**Comment by Jean-BaptisteC** [comment]
We cannot doing something if developers use a version name weird.
I have just one solution maybe reanalyse apps if it's not the last version, maybe developer has changed version name.
