### ISSUE TITLE
Could you please accept translation request at crowdin?

### ISSUE THREAD

**Issue by Oymate** [Exodus-Privacy/exodus-android-app#79]
Title, thanks!

**Comment by simpnu** [comment]
Hello @Oymate 
We are currently migrating our translations into https://crowdin.com/project/exodus-android-app

I'm guessing translation requests will be opened once this migration is performed

**Comment by Schoumi** [comment]
Hi @Oymate 
I've migrating all translations into https://crowdin.com/project/exodus-android-app
Tell me if the settings allow you to do what you want to. I'll correct them if it's not.

**Comment by Oymate** [comment]
@Schoumi
Hey, can you add Bengali option too?
Thanks!

**Comment by Schoumi** [comment]
I've added bengali.

**Comment by Porrumentzio** [comment]
Add Basque (eu) option to translate, please!

**Comment by Oymate** [comment]
@Porrumentzio Please ask on crowdin, if they do not answer in a week or so open a new issue.  :)

**Comment by pnu-s** [comment]
@Porrumentzio I just added Basque to Crowdin ;) 
https://crowdin.com/project/exodus-android-app

**Comment by Porrumentzio** [comment]
Thanks! I almost finished it!
