### ISSUE TITLE
Add an option to submit an app

### ISSUE THREAD

**Issue by tdelmas** [Exodus-Privacy/exodus-android-app#8]

**Comment by Porkepix** [comment]
Would be nice also adding a way to do a new analyze for updates apps (could either be checked online, or if the local version is higher than the remote one. First way is more accurate, but second way is more privacy-proof).

**Comment by jawz101** [comment]
This app is pretty useless unless I can submit.

I wouldn't think it even requires uploading the app from my device if you're just processing the package's Play Store URL server-side.

I could see either implementing it as

1) extract package name
2) use that to build the Play Store URL

Or, have this app register as a share action provider for when you're in the play store

https://developer.android.com/training/sharing/shareaction

Click on the share button when you're looking at an app and it passes the URL to you all, it scans and displays the results.

**Comment by simpnu** [comment]
I think the application could just add a link such as the following one (as does Exodify) for any application which is not yet scanned by Exodus:

https://reports.exodus-privacy.eu.org/analysis/submit/#<application_handle>

**Comment by simpnu** [comment]
@Schoumi Is this blocked by https://github.com/Exodus-Privacy/exodus/issues/163?

**Comment by Schoumi** [comment]
@simpnu no it not block this but it will be better if it is done someday to bring a better experience

**Comment by jawz101** [comment]
Some users will expect it to be an option.  Plus, there are so many apps not uploaded to the site.  There have been a few times where I open the site and copy/paste several package names just too see what they contain.  It's a bit cumbersome.

**Comment by jawz101** [comment]
Or at least show an app's package name, and have a link to the submission page where I can copy/paste the package name.

**Comment by pnu-s** [comment]
@Schoumi Do you know when this will be added to the exodus app? :pray:

**Comment by jawz101** [comment]
There is no point to the Exodus app without the ability to submit apps.

**Comment by jawz101** [comment]
I guesstimate there are only about 80,000 apps in the Exodus database?  Just curious if there will be any update

**Comment by pnu-s** [comment]
80500+ apps indeed, you can find the number here: https://reports.exodus-privacy.eu.org/en/reports/list/

I'll try to see if I can raise this point, but tbh we don't have a lot of people working on this app unfortunately

**Comment by yoshimo** [comment]
IMHO this should include the device you run it on.
Applications are gated behind device features and regions so if exodus fails to download we might fm figure out why with additional info about the device the request and app come from

**Comment by Jean-BaptisteC** [comment]
With the next release
from share menu on Android, you can check if reports already exists in Exodus
This function works with app links to google play or fdroid and directly from app google play or app fdroid

**Comment by Jean-BaptisteC** [comment]
In version 3.0, it's planned to rework this function.
From Google Play or Fdroid, you can show report from share menu.
In version 3.0 pop-up is replaced by fragments on app, pop-up is show only if app has never analysed to submit app
And apps present on exodus app and never analysed, we want add [icon ](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apolicy%3A)for submit app

**Comment by yoshimo** [comment]
Manually submitting is still odd. Have a local marker if we submitted a certain application version successfully  before and if not  push it to all supported stores automatically
