### ISSUE TITLE
New Basque translation completed on Crowdin, please merge it

### ISSUE THREAD

**Issue by Porrumentzio** [Exodus-Privacy/exodus-android-app#84]

**Comment by comradekingu** [comment]
Crowdin is as far removed from privacy it gets. See https://github.com/jitsi/jitsi-meet/issues/5056#issuecomment-612239691
Use Weblate instead :)

**Comment by Porrumentzio** [comment]
Thanks! I read somewhere that Crowdin is the translation place for Exodus, so it must be changed to avoid confusions. Which is the link to weblate for Exodus?

**Comment by Porrumentzio** [comment]
In the official website on the [Contribute page](https://exodus-privacy.eu.org/en/page/contribute/), it is the link to Crowdin to translate:
![irudia](https://user-images.githubusercontent.com/61913683/91701056-096d1200-eb77-11ea-9a6c-aa6b93b413b0.png)

**Comment by comradekingu** [comment]
None yet, but hopefully someone notices https://github.com/Exodus-Privacy/exodus-android-app/issues/86 :)

**Comment by Jean-BaptisteC** [comment]
With 3.0.0 version, i have added and updated translations on Crowdin
I close this issue
