### ISSUE TITLE
(Request) Copy tracker link for adding in AdAway/Hosts file

### ISSUE THREAD

**Issue by Cruysen** [Exodus-Privacy/exodus-android-app#89]
Hello,

Is it possible to make a copy field in the Trackers page with the link of this tracker? 
Or a button to add this Tracker directly in [AdAway](https://github.com/adaway) 
Or to add directly in the hosts file? (needs root probably)

With this we can reduce all the communication with the trackers used in the apps that we don't want/need.

**Comment by jawz101** [comment]
Adaway list maintainer here.  I've contributed quite a bit of tracker info to the Exodus project myself.  I wouldn't worry too much about DNS entries found on Exodus ending back up in the Adaway list.
