### ISSUE TITLE
Add an option to export a report

### ISSUE THREAD

**Issue by RoneoOrg** [Exodus-Privacy/exodus-android-app#94]
Hi,

the objective is to compare the state of a device before and after some operations  
For example: switching from stock ROM and his bloatware   to  AOSP / Lineage  /   /e/

It could be an effective way to promote open-source ROM and projects

**Comment by RoneoOrg** [comment]
Bonus: make it easy to generate a `diff` between to different reports

**Comment by Jean-BaptisteC** [comment]
Maybe you use our API REST to do that?
