### ISSUE TITLE
Can an app still use resources even if it is not permitted to access them?

### ISSUE THREAD

**Issue by pallavJha** [Exodus-Privacy/exodus-android-app#95]
Hi,

In the Exodus Report, this App appears to have 36 permissions:
![Screenshot_20210804-222844.png](https://user-images.githubusercontent.com/4998915/128222987-8918ecf7-c769-4f69-ac89-229e8dc36549.png)

But the settings app shows something else:
![Screenshot_20210804-222813.png](https://user-images.githubusercontent.com/4998915/128223004-232f12e6-53cf-4884-b6a5-384c170059ca.png)

Here, the Camera permission is disabled but Exodus shows that the App can still access it.

I wanted to know which one is correct, or if I'm missing any info here.

Thanks!

**Comment by Jean-BaptisteC** [comment]
Hi, exodus show the list of permissions than can be use by applications but exodus don't say if permissions is enabled or disabled on your smartphone.
