### ISSUE TITLE
Number show is not correct

### ISSUE THREAD

**Issue by Jean-BaptisteC** [Exodus-Privacy/exodus-android-app#96]
Number show during  "Processing Applications:" is everytime different, then, i don't donwload new applications or update my smartphone. I have update list of applications on exodus privacy range on two minutes.

**Comment by ItsIgnacioPortal** [comment]
Can't reproduce on v2.2.1 Android 9, Moto e6 plus

**Comment by Jean-BaptisteC** [comment]
This bug is not present on 3.0, because this information doesn't exist.
