### ISSUE TITLE
Installed app on device missing from Exodus app's listing

### ISSUE THREAD

**Issue by Android-X13** [Exodus-Privacy/exodus-android-app#97]
Assuming that all installed apps should appear in Exodus app...

Apps that are installed on my device but haven't been analysed by Exodus appear in the app's list with a description: "This app hasn't been analyser by Exodus Privacy yet".

However there's one app that isn't picked up as installed on the device and is not shown in Exodus app's list at all:

Activity Manager (com.activitymanager) downloaded from F-Droid.

**Comment by Jean-BaptisteC** [comment]
Exodus-Privacy/exodus#477

**Comment by pnu-s** [comment]
Closing this following the explanation from @Jean-BaptisteC 

Once the report (from the Fdroid app) is present on exodus, it should appear in the app too.

**Comment by Android-X13** [comment]
@pnu-s I'm sorry but I don't follow. Right now I can see in Exodus an app that says "This app hasn't been analysed by Exodus Privacy yet",  so it doesn't yet have any report, but it does appear in the list. The other apps that I mentioned above didn't appear at all (by the way, now both of them appear and they do have a report).
